### ISSUE TITLE
not able to disassemble correctly

### ISSUE THREAD

**Issue by etacheau** [vrtadmin/CASC#8]
While working on a new malware, it's not able to provide disassembly correctly.
sha256 of the malware: 1f63371f2b2a5f340ea3c4d211b1fe0d6197e3a00e87cae49e873ae8964e8810

![bug1](https://cloud.githubusercontent.com/assets/7734701/24382468/bcbf331c-1356-11e7-9e94-4badfd81d7ef.PNG)
![bug2](https://cloud.githubusercontent.com/assets/7734701/24382474/c1150d2e-1356-11e7-89ce-70de562eb0e8.PNG)

**Comment by demonduck** [comment]
This is due to the way the Assembly is derived from the binary. This is occurring since the highlighted code is not part of a function. I'll look into if it is possible to change this behavior.

**Comment by demonduck** [comment]
The dev branch has a fix for this issue, please test it out and reopen this issue to report any issues you encounter.
